### PR TITLE
Demo code

### PR DESCRIPTION
**Pull request by lizalc**

### CODE REVIEW

**Review by Janak-Patel — DISMISSED** [review]

**Comment by lizalc** [comment]
This isn't ready for review or approval yet. I've still got to add the RGB LED support.

**Comment by lizalc** [comment]
When I'm done with my changes I'll let you know.

**Comment by lizalc** [comment]
I've added support for the RGB LED and have also added support for a configuration file for storing the IoT Device primary ID and the time delay to be used between program loop iterations.

Still wanting to get the cellular modem to auto connect, haven't yet finished that.

**Comment by lizalc** [comment]
I've added a `systemd` service and associated scripts / config for managing the cellular connection to the `systemd` folder. Once the service is installed it can be auto-started at boot or simply used as an easier way to start and stop the network connection.

**Comment by lizalc** [comment]
Ready for review. Look this over soon so we can address anything needed before the Demo day. I can also add more devices to my IoT hub so we can all share that rather than creating one individually for testing the Azure connection. If you want me to create a device for you in Azure let me know and I'll send the primary key that gets generated.

**Review by Janak-Patel — APPROVED** [review]
I looked over the demo code and everything looks fine. I don't know much about the cell modem files so, I don't have anything to say about it. However, I was wondering how will you share your IoT Hub? Have you found a way to share it such that we can see the hub settings and change it if needed? Or is it just you creating the IoT Devices on the hub and only sharing the primary key?

**Comment by lizalc** [comment]
I can create the device in the IoT Hub I created and then share the primary key for that device and share the resources / PowerBI dashboard.

**Pull request merged**
